# Generated by Django 4.2.1 on 2023-05-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_commentcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentcontent',
            name='userc',
            field=models.CharField(default='temp2', max_length=65),
        ),
    ]
