# Generated by Django 4.2.1 on 2023-05-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userw', models.CharField(default='temp2', max_length=65)),
                ('prwd', models.IntegerField(default=0)),
            ],
        ),
    ]
