# Generated by Django 4.2.1 on 2023-05-31 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='il',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='wt',
            field=models.CharField(default='', max_length=65),
        ),
    ]
